name: Backend CI

on:
  push:
    paths:
      - '**/*.java'
      - 'pom.xml'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - '**/*.java'
      - 'pom.xml'
      - '.github/workflows/backend-ci.yml'

permissions:
  contents: read

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  JACOCO_MIN_LINE: '0.20'   # ajusta si quieres exigir más cobertura

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build & Test (profile=test + JaCoCo)
        run: mvn -B -U clean verify -Dspring.profiles.active=test -Djacoco.min.line=${{ env.JACOCO_MIN_LINE }}

      - name: Upload test & coverage reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-and-jacoco
          path: |
            target/surefire-reports
            target/failsafe-reports
            target/jacoco.exec
            target/site/jacoco/*
          if-no-files-found: ignore
